### PR TITLE
Feedback table (rebased ✅)

### PR DESCRIPTION
**Pull request by jackcarlisle**
# ready for review 

- [x] adds feedback table + tests #29 
- [x] adds pre-commit hook #31

### CODE REVIEW

**Comment by jackcarlisle** [comment]
@nelsonic my test coverage locally is 100%. The remote test coverage was 100% before the rebase as well but it's gone down to 87.5% now. Looking into why this is the case.

screen shot 2017-05-03 at 14 16 51

**Comment by nelsonic** [comment]
@jackcarlisle please _assign_ for review when you think it's ready. 😉 
I _want_ to approve your timesheet/invoice but need to clear down the PR backlog _first_. 👍

**Comment by jackcarlisle** [comment]
@nelsonic I've been looking into why the coverage has dropped and I think it will get back up to 100% after the next PR is merged. It's got something to do with not having any feedback controller tests which means that the model isn't hit. I think the next PR will solve this though so I'm going to assign this as ready

**Review by nelsonic — APPROVED** [review]
@jackcarlisle do you want to add `.env` to `.gitignore` and reset the AWS secrets (_ASAP_) then re-assign to me for merging?

**Comment by jackcarlisle** [comment]
@nelsonic yeah sorry just saw that!

**Comment by jackcarlisle** [comment]
@nelsonic secrets changed, ignored and deleted from AWS

**Comment by nelsonic** [comment]
@jackcarlisle cool. thanks for confirming. merging now. 👍 
https://vimeo.com/50600813

**Pull request merged**
